name: Build Samples

on:
    push:
        branches: [ '*' ]
    pull_request:
        branches: [ '*' ]
    repository_dispatch:
        types: [ build ]
    schedule:
        - cron: '0 0 * * 1'

jobs:
    build-PlacesSnippets:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Install CocoaPods
          run: |
              sudo gem install cocoapods
    
        - name: Run pod install
          run: |
              pod install --project-directory=snippets/PlacesSnippets
    
        - name: Build project
          run: |
            echo "Building"
            xcodebuild -workspace snippets/GoogleMapsDemos.xcworkspace \
            -scheme PlacesSnippets \
            -destination platform\=iOS\ Simulator,OS\=13.3,name\=iPhone\ 8 build | xcpretty

    build-GoogleMaps:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Install CocoaPods
          run: |
              sudo gem install cocoapods
    
        - name: Run pod install
          run: |
              pod install --project-directory=GoogleMaps/
    
        - name: Build project
          run: |
            echo "Replacing #error for API key"
            sed -i .prev '/#error/'d GoogleMaps/GoogleMapsDemos/SDKDemoAPIKey.h
    
            echo "Building"
            xcodebuild -workspace GoogleMaps/GoogleMapsDemos.xcworkspace \
            -scheme GoogleMapsDemos \
            -destination platform\=iOS\ Simulator,OS\=13.3,name\=iPhone\ 8 build | xcpretty

    build-GooglePlaces:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Install CocoaPods
          run: |
              sudo gem install cocoapods
    
        - name: Run pod install
          run: |
              pod install --project-directory=GooglePlaces/
    
        - name: Build project
          run: |
            echo "Replacing #error for API key"
            sed -i .prev '/#error/'d GooglePlaces/GooglePlacesDemos/SDKDemoAPIKey.h
    
            echo "Building"
            xcodebuild -workspace GooglePlaces/GooglePlacesDemos.xcworkspace \
            -scheme GooglePlacesDemos \
            -destination platform\=iOS\ Simulator,OS\=13.3,name\=iPhone\ 8 build | xcpretty

    build-current-place-on-map:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Install CocoaPods
          run: |
              sudo gem install cocoapods
    
        - name: Run pod install
          run: |
              pod install --project-directory=tutorials/current-place-on-map/
    
        - name: Build project
          run: |
            echo "Building"
            xcodebuild -workspace tutorials/current-place-on-map.xcworkspace \
            -scheme current-place-on-map \
            -destination platform\=iOS\ Simulator,OS\=13.3,name\=iPhone\ 8 build | xcpretty

    build-map-with-marker:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Install CocoaPods
          run: |
              sudo gem install cocoapods
    
        - name: Run pod install
          run: |
              pod install --project-directory=tutorials/map-with-marker/
    
        - name: Build project
          run: |
            echo "Building"
            xcodebuild -workspace tutorials/map-with-marker.xcworkspace \
            -scheme map-with-marker \
            -destination platform\=iOS\ Simulator,OS\=13.3,name\=iPhone\ 8 build | xcpretty

    build-places-address-form:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Install CocoaPods
          run: |
              sudo gem install cocoapods
    
        - name: Run pod install
          run: |
              pod install --project-directory=tutorials/places-address-form/
    
        - name: Build project
          run: |
            echo "Building"
            xcodebuild -workspace tutorials/places-address-form.xcworkspace \
            -scheme places-address-form \
            -destination platform\=iOS\ Simulator,OS\=13.3,name\=iPhone\ 8 build | xcpretty

    build-MapsPlacesDemo-form:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install CocoaPods
          run: |
              sudo gem install cocoapods

        - name: Run pod install
          run: |
              pod install --project-directory=MapsAndPlacesDemo/

        - name: Build project
          run: |
            echo "Replacing #error for API key"
            sed -i .prev '/#error/'d MapsAndPlacesDemo/MapsAndPlacesDemo/ApiKeys.swift

            echo "Building"
            xcodebuild -workspace MapsAndPlacesDemo/MapsAndPlacesDemo.xcworkspace \
            -scheme MapsAndPlacesDemo \
            -destination platform\=iOS\ Simulator,OS\=13.3,name\=iPhone\ 11 build
